CREATE OR REPLACE DATABASE db1;
CREATE SCHEMA sh1;

CREATE TABLE sh1.t1(c1 int);

CREATE FUNCTION public.test()
RETURNS NUMBER
LANGUAGE SQL
AS '1';

CREATE VIEW sh1.v1 AS
SELECT *, test() c2 FROM t1;

CREATE SCHEMA sh2;

CREATE FUNCTION sh2.test()
RETURNS NUMBER
LANGUAGE SQL
AS '2';

CREATE TABLE sh2.t2(c1 int);

CREATE VIEW sh2.v2 AS
SELECT *, test() c2 FROM t2;

